### ISSUE TITLE
jumpgate compute servers not honoring query params for marker & limit

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#72] opened 2014-03-24 13:04 UTC
It does not appear that jumpgate's compute (server) driver is honoring the `marker` and `limit` params on a GET /servers call.

As per http://api.openstack.org/api-ref-compute-v2.html  a `GET v2/​{tenant_id}​/servers` should support a limit and marker as follows:

```
marker (Optional)   query   csapi:UUID  
UUID of the server at which you want to set a marker.

limit (Optional)    query   xsd:int 
Integer value for the limit of values to return.
```

Based on the current jumpgate compute sl driver I do see some code for these around here: https://github.com/softlayer/jumpgate/blob/master/jumpgate/compute/drivers/sl/servers.py#L274

However when I try to use limit and marker I'm getting back my entire list of servers..

For example:

```
GET http://JUMPGATE_IP:JUMPGATE_PORT/compute/v2/MY_ACCOUNT/servers/detail?limit=21&marker=3912018&project_id=MY_ACCOUNT
```

Returns all CCIs in my account rather than a max of 21 as requested above.

I didn't have time to dig into this one yet, but I will try to find more details as time permits.

**Comment by Neetuj** [comment] 2014-04-25 16:02
I think the limit is not working because its hardcoded to None https://github.com/softlayer/jumpgate/blob/master/jumpgate/compute/drivers/sl/servers.py#L275

**Comment by beittenc** [comment] 2014-04-25 16:04
@Neetuj The limit is set over the following three lines. If there is a limit parameter in the request, it will attempt to cast it to an integer. That's how the limit is actually being set.

**Comment by Neetuj** [comment] 2014-04-25 16:12
@beittenc  you are right .. its is set correctly and i verified it works by testing it  ..'http://localhost:5000/compute/v2/13193/servers/detail?limit=1'

**Comment by sudorandom** [comment] 2014-04-25 16:12
@Neetuj the first step to solving any bug is to replicate the issue. I'm unable to do that. It appears that both limit and marker are applied. At least with the /compute/v2/ACCOUNT_ID/servers/detail endpoint.

**Comment by Neetuj** [comment] 2014-04-25 16:14
i was able to test limit .. but not the marker

**Comment by Neetuj** [comment] 2014-04-25 16:58
OK tested it limit and marker both are working .. BTW if i give a invalid marker UUID (say 1) it does not complain

**Comment by sudorandom** [comment] 2014-04-29 14:18
I'm going to go ahead and close this until we can reproduce the problem.

**Closed as completed by sudorandom** 2014-04-29 14:18 UTC
Labels: bug, os-compute
