### ISSUE TITLE
EndpointNotFound  for "nova volume"

### ISSUE THREAD

**Issue by Neetuj** [softlayer/jumpgate#103] opened 2014-05-15 19:24 UTC
volume endpoints are not loading up correctly ...
 “nova --debug volume-list” 

 results into :-

DEBUG (shell:792) 
Traceback (most recent call last):
  File "/opt/stack/python-novaclient/novaclient/shell.py", line 789, in main
    OpenStackComputeShell().main(argv)
  File "/opt/stack/python-novaclient/novaclient/shell.py", line 693, in main
    self.cs.authenticate()
  File "/opt/stack/python-novaclient/novaclient/v1_1/client.py", line 194, in authenticate
    self.client.authenticate()
  File "/opt/stack/python-novaclient/novaclient/client.py", line 410, in authenticate
    auth_url = self._v2_auth(auth_url)
  File "/opt/stack/python-novaclient/novaclient/client.py", line 501, in _v2_auth
    return self._authenticate(url, body)
  File "/opt/stack/python-novaclient/novaclient/client.py", line 516, in _authenticate
    return self._extract_service_catalog(url, resp, respbody)
  File "/opt/stack/python-novaclient/novaclient/client.py", line 344, in _extract_service_catalog
    volume_service_name=self.volume_service_name,)
  File "/opt/stack/python-novaclient/novaclient/service_catalog.py", line 84, in url_for
    raise novaclient.exceptions.EndpointNotFound()
EndpointNotFound
ERROR (EndpointNotFound):

**Comment by Neetuj** [comment] 2014-05-15 19:25
upon further investigation is seems like its because block_storage stills exists in the project ( i think it was supposed to be replaces by volume) .. am working on replacing it to see if that fixes it

**Comment by Neetuj** [comment] 2014-05-15 19:26
https://github.com/softlayer/jumpgate/search?q=block_storage&type=Code

**Comment by sudorandom** [comment] 2014-05-15 19:28
@Neetuj  This is likely a duplicate of: #76

There's essentially zero support for volumes/block storage at this time.

**Closed as completed by sudorandom** 2014-05-15 19:28 UTC

**Comment by sudorandom** [comment] 2014-05-15 19:31
@Neetuj on that note, if the endpoint name needs to change, make sure #76 is mentioned so we can track that work there.

**Comment by Neetuj** [comment] 2014-05-15 19:37
got it !

**Comment by sudorandom** [comment] 2014-05-15 19:38
@Neetuj It's perfectly valid to work on. I just didn't want duplicate issues. Sorry for the confusion.
